version: '2'
services:
    redis:
        image: redis

    backend:
        build: .
        ports:
            - 8000:8000
        env_file: .env
        depends_on:
          - redis

    worker:
        build: .
        env_file: .env
        command: celery -A celerydemo worker -l info
        depends_on:
          - redis

    flower:
        build: .
        env_file: .env
        command: celery -A celerydemo flower
        ports:
            - 5555:5555
        depends_on:
            - redis

    frontend:
        build: frontend
        ports:
            - 80:80
        env_file: .env
        depends_on:
          - backend
          - flower